feat: create log in front page
GSG-G11/InstaMart pull request #39
Opened 2022-04-23 19:41 UTC by MahmoudJD95

2022-04-24 11:21 UTC, MahmoudJD95 commented
<img width="1432" alt="Screen Shot 2022-04-24 at 2 20 40 PM" src="https://user-images.githubusercontent.com/81965438/164973948-12fe8557-c038-465e-9513-2d741e1ac76b.png">

2022-04-24 19:18 UTC, aaamra requested changes

2022-04-24 19:18 UTC, aaamra commented on client/src/Components/Login.jsx
> +  }, [data]);
I think this `useEffect` is not necessary. you can add the `login` function in the `handelSubmit` function

2022-04-25 07:14 UTC, aaamra commented on client/src/Components/Login.jsx
> +    });
this state is unnecessary to you can pass the email and password without setting it

2022-04-25 20:43 UTC, SalmaIssa96 approved these changes

2022-04-25 20:44 UTC, Ibrahim-Jarada approved these changes

2022-04-25 20:45 UTC, merged