feat: create get product by id route
GSG-G11/InstaMart pull request #51
Opened 2022-04-24 22:59 UTC by SalmaIssa96

2022-04-25 01:09 UTC, Ibrahim-Jarada submitted a review, later dismissed

2022-04-25 01:58 UTC, MahmoudJD95 submitted a review, later dismissed

2022-04-25 08:29 UTC, yousrakhaleel approved these changes

2022-04-25 09:13 UTC, aaamra requested changes
write the tests for this route

2022-04-25 21:20 UTC, yousrakhaleel submitted a review, later dismissed

2022-04-25 22:24 UTC, yousrakhaleel approved these changes

2022-04-25 22:27 UTC, aaamra submitted a review, later dismissed

2022-04-26 10:50 UTC, Ibrahim-Jarada requested changes

2022-04-26 10:50 UTC, Ibrahim-Jarada commented on server/src/controllers/products/getProductByID.ts
> +    if (err.details) {
ensure that you don't send twice.
```suggestion
if (err.details) {
    return  res.status(422).json({ msg: err.details[0].message, status: 422 });
    }
  return  next(err);
  }```

2022-04-26 11:07 UTC, Ibrahim-Jarada approved these changes

2022-04-26 12:45 UTC, yousrakhaleel approved these changes

2022-04-26 19:47 UTC, MahmoudJD95 approved these changes

2022-04-26 19:47 UTC, merged