52 product details component
GSG-G11/InstaMart pull request #64
Opened 2022-04-27 01:11 UTC by SalmaIssa96

![‏‏لقطة الشاشة (383)](https://user-images.githubusercontent.com/88354453/165418258-5b0df141-5242-4775-aec7-3c6119d94f51.png)
![‏‏لقطة الشاشة (384)](https://user-images.githubusercontent.com/88354453/165418262-11c7dcb0-b993-448d-aea4-87119222f480.png)

2022-04-27 11:52 UTC, aaamra requested changes
Great Work @SalmaIssa96 

but i have some small notes
to organize your files and make them more readable
change this file names:
- `client/src/Components/productdetails/ProductDetails.jsx` => `client/src/Components/ProductDetailsCard/index.jsx`
- `client/src/Components/productdetails/index.css` => `client/src/Components/ProductDetailsCard/style.css`
- `client/src/Pages/productdetailsPage/ProductDetailsPage.jsx` => `client/src/Pages/ProductDetails/index.jsx`
- `client/src/Pages/productdetailsPage/index.css` => `client/src/Pages/ProductDetails/style.css`

2022-04-27 12:32 UTC, yousrakhaleel approved these changes

2022-04-27 13:15 UTC, aaamra approved these changes

2022-04-27 15:01 UTC, yousrakhaleel approved these changes

2022-04-28 18:53 UTC, Ibrahim-Jarada approved these changes

2022-04-28 18:58 UTC, MahmoudJD95 approved these changes

2022-04-28 18:58 UTC, merged