feat:create order controller
GSG-G11/InstaMart pull request #83
Opened 2022-05-07 07:08 UTC by MahmoudJD95

2022-05-07 08:10 UTC, Ibrahim-Jarada requested changes

2022-05-07 08:10 UTC, Ibrahim-Jarada commented on server/src/controllers/validation/orderProductValidation.ts
> +    productArray: Joi.string().required(),
Is productArray a string?

2022-05-07 08:10 UTC, Ibrahim-Jarada commented on server/src/controllers/orders/index.ts
> +// import { CustomizedError } from '../../utilities';
Uncomment this if and only if you follow my suggestions below then you will use it or you will need to remove this line

2022-05-10 10:20 UTC, Ibrahim-Jarada approved these changes

2022-05-10 10:38 UTC, aaamra approved these changes

2022-05-10 10:41 UTC, SalmaIssa96 approved these changes

2022-05-10 11:00 UTC, yousrakhaleel approved these changes

2022-05-10 11:00 UTC, merged